export type News = {
  news_id: number;
  published_at: string;
  publisher: string;
  thumbnail: string;
  origin_url: string;
  title_en: string;
  content_en: string;
  summary_en: string;
  title_ko: string;
  content_ko: string;
  summary_ko: string;
  title_fr: string;
  content_fr: string;
  summary_fr: string;
  title_ja: string;
  content_ja: string;
  summary_ja: string;
  title_zh: string;
  content_zh: string;
  summary_zh: string;
  view: number;
};
